name: Deploy GitHub pages

on:
  push:
    branches:
      - master

env:
  GH_PAGES_DIR: gh-pages-dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --env out=$GH_PAGES_DIR
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ${{ env.GH_PAGES_DIR }} # The folder the action should deploy.
          clean: true
